theme: jekyll-theme-architect
title: Using LIDAR to Determine Effects of Changes in Sea Level
description: This study utilizes LIDAR to build a terrain model in order to determine the effects of increased sea level.
